# spell-checker:ignore tsuyoshicho

name: lint

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: tsuyoshicho/action-textlint@v3
        with:
          textlint_flags: "hon/**/*.md"

  spell:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v6
